from django.db import migrations, models

def apply_migration(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            for table in ['habitusapp_admin', 'habitusapp_aluno', 'habitusapp_professor']:
                cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{table}_pkey" CASCADE;')
                cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "matricula" DROP NOT NULL;')
                cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;')
    elif schema_editor.connection.vendor == 'sqlite':
        pass

def rollback_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0023_remove_admin_abdomen_remove_admin_abdominal_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="admin",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                migrations.AddField(
                    model_name="aluno",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                migrations.AddField(
                    model_name="professor",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                migrations.AlterField(
                    model_name="admin",
                    name="matricula",
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name="aluno",
                    name="matricula",
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name="professor",
                    name="matricula",
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_migration, rollback_migration),
            ]
        )
    ]
