# Generated by Django 4.2.7 on 2026-06-30 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitusapp", "0039_alter_noticia_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmacaoSenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=100, unique=True
                    ),
                ),
                ("nova_senha", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacao_senha",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
