services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Cria um volume persistente para a pasta de dados
      - ./data:/usr/src/python/app/devadmin/data
    environment:
      - PYTHONUNBUFFERED=1